spring:
  application:
    name: demoMyBank
  datasource:
    url: jdbc:postgresql://localhost:5435/fhne99
    username: fhne99
    password: fhne99
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 3600
